name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Create release archive
      run: |
        zip -r openbuild-dist.zip dist/
        tar -czf openbuild-dist.tar.gz dist/
        
    - name: Generate release notes
      id: release_notes
      run: |
        echo "### 🎉 OpenBuild Release ${{ github.ref_name }}" > release_notes.md
        echo "" >> release_notes.md
        echo "#### What's Changed" >> release_notes.md
        git log --oneline $(git describe --tags --abbrev=0 2>/dev/null || echo "")..HEAD >> release_notes.md || echo "Initial release" >> release_notes.md
        echo "" >> release_notes.md
        echo "#### Attribution" >> release_notes.md
        echo "OpenBuild was originally created by **Grandillionaire (Maximillian Grand)**" >> release_notes.md
        echo "" >> release_notes.md
        echo "#### Installation" >> release_notes.md
        echo "\`\`\`bash" >> release_notes.md
        echo "# Clone the repository" >> release_notes.md
        echo "git clone https://github.com/${{ github.repository }}.git" >> release_notes.md
        echo "cd openbuild" >> release_notes.md
        echo "" >> release_notes.md
        echo "# Install dependencies" >> release_notes.md
        echo "npm install" >> release_notes.md
        echo "" >> release_notes.md
        echo "# Start development server" >> release_notes.md
        echo "npm run dev" >> release_notes.md
        echo "\`\`\`" >> release_notes.md
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: release_notes.md
        files: |
          openbuild-dist.zip
          openbuild-dist.tar.gz
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}